import type { Chapter, Lesson } from '../types/protocol'

/* ── 课程自动发现 ──────────────────────────────────────
   C++ 课程：以 p*-l* 命名的课程文件自动注册。
   SQL/数据库课程：以 db-* 命名的课程文件自动注册。
   新课程只需在 courses/ 下创建文件即可自动发现，
   无需手动编写 import/export 代码。                    */

const cppCourseModules = import.meta.glob<{ default: Lesson }>(
  './p*-l*.ts',
  { eager: true },
)

const dbCourseModules = import.meta.glob<{ default: Lesson }>(
  './db-*.ts',
  { eager: true },
)

export const courses: Lesson[] = [
  ...Object.values(cppCourseModules).map((m) => m.default),
  ...Object.values(dbCourseModules).map((m) => m.default),
]

export const chapters: Chapter[] = [
  {
    id: 'icebreaking',
    badge: '起点',
    title: '破冰——认识代码',
    description: '从零开始，认识程序、代码、符号，建立编程的基本认知。',
    courseIds: [
      'what-is-program',
      'code-is-text',
      'symbols-you-see',
      'first-program-glance',
      'practice-1',
    ],
  },
  {
    id: 'values-variables-types',
    badge: '基础',
    title: '基础积木（上）',
    description: '值、变量、类型——编程世界最基本的积木。',
    courseIds: [
      'what-is-value',
      'what-is-name',
      'int-type',
      'double-type',
      'char-type',
      'bool-type',
      'practice-types',
      'declare-variable',
      'assign-value',
      'equals-is-assign',
      'semicolon-rule',
      'declare-and-init',
      'practice-var-declare',
      'type-mismatch',
      'phase1-review',
    ],
  },
  {
    id: 'operators-io-flow',
    badge: '基础',
    title: '基础积木（下）',
    description: '算术运算、输入输出、条件判断——程序的核心逻辑能力。',
    courseIds: [
      'arithmetic-plus-minus',
      'multiply-divide-mod',
      'integer-division-trap',
      'operator-precedence',
      'practice-arithmetic',
      'cout-basics',
      'cout-multiple',
      'cin-basics',
      'cin-cout-combo',
      'practice-io',
      'comparison-six',
      'comparison-result',
      'if-intro',
      'if-braces',
      'if-else',
      'equals-vs-assign',
      'practice-conditions',
      'practice-comprehensive',
      'practice-all-p2',
      'phase2-review',
    ],
  },
  {
    id: 'loops-and-arrays',
    badge: '分水岭',
    title: '循环与数组',
    description: '循环让代码重复执行，数组让数据成批管理——编程的第一个分水岭。',
    courseIds: [
      'why-loops',
      'while-basics',
      'while-counter',
      'infinite-loop',
      'for-basics',
      'for-vs-while',
      'do-while',
      'practice-loops',
      'array-concept',
      'array-index',
      'loop-and-array',
      'practice-loops-arrays',
    ],
  },
  {
    id: 'strings-functions',
    badge: '进阶',
    title: '模块化思维',
    description: '字符串处理、函数封装、作用域规则——写出可复用代码。',
    courseIds: [
      'string-init',
      'string-concat',
      'string-index-size',
      'string-input',
      'practice-string',
      'why-functions',
      'function-definition',
      'function-call',
      'function-return',
      'void-function',
      'function-parameters',
      'multiple-parameters',
      'practice-functions',
      'what-is-scope',
      'local-vs-global',
      'scope-nesting',
      'practice-scope',
    ],
  },
  {
    id: 'pointers-refs-overload',
    badge: '进阶',
    title: 'C++ 特色',
    description: '指针、引用、重载、多文件——进入 C++ 特有的工程世界。',
    courseIds: [
      'pointer-motivation',
      'address-of-operator',
      'pointer-variable',
      'dereference-operator',
      'star-two-meanings',
      'nullptr',
      'reference-intro',
      'ref-vs-ptr',
      'pass-by-value',
      'pass-by-reference',
      'function-overload',
      'default-arguments',
      'practice-ptr-ref',
      'separate-compilation',
      'practice-organization',
    ],
  },
  {
    id: 'debugging-mindset',
    badge: '技能',
    title: '调试思维',
    description: '不会调试等于不会编程——读懂错误、打印调试、断点观察。',
    courseIds: [
      'what-is-debugging',
      'reading-errors',
      'print-debugging',
      'breakpoint-concept',
      'step-over-into',
      'watch-variables',
      'practice-debugging',
    ],
  },
  {
    id: 'oop-foundation',
    badge: '核心',
    title: 'OOP 地基',
    description: '类与对象、封装、构造析构——面向对象编程的核心思想。',
    courseIds: [
      'why-class',
      'define-class',
      'create-object',
      'member-access',
      'public-vs-private',
      'member-functions',
      'practice-class',
      'struct-vs-class',
      'constructor-intro',
      'constructor-overload',
      'init-list',
      'init-order',
      'destructor-intro',
      'practice-ctor-dtor',
      'this-pointer',
      'static-members',
      'const-member-func',
      'class-separation',
      'practice-oop-fund',
      'phase7-review',
    ],
  },
  {
    id: 'inheritance-polymorphism',
    badge: '核心',
    title: '继承与多态',
    description: 'OOP 的灵魂——代码复用、多态、虚函数、抽象接口。',
    courseIds: [
      'why-inheritance',
      'inheritance-basics',
      'protected-access',
      'inheritance-modes',
      'construction-chain',
      'practice-inheritance',
      'why-polymorphism',
      'virtual-function',
      'override-specifier',
      'polymorphism-in-action',
      'virtual-destructor',
      'abstract-class',
      'interface-design',
      'practice-polymorphism',
      'object-slicing',
      'diamond-problem',
      'phase8-review',
    ],
  },
  {
    id: 'cpp-idioms',
    badge: '黑话',
    title: 'C++ 黑话入门',
    description: 'const 的六种面孔、static、友元、运算符重载——C++ 特有的语法武器。',
    courseIds: [
      'const-value',
      'const-ptr',
      'const-ref',
      'const-methods',
      'const-overload',
      'practice-const',
      'static-local',
      'static-in-class-review',
      'friend-function',
      'friend-class',
      'why-operator-overload',
      'op-overload-syntax',
      'overload-arithmetic',
      'overload-stream',
      'overload-rules',
      'practice-op-overload',
      'phase9-review',
    ],
  },
  {
    id: 'memory-war',
    badge: '分水岭',
    title: '内存战争',
    description: '堆与栈、new/delete、深浅拷贝、RAII、移动语义——C++ 最核心的内存管理。',
    courseIds: [
      'stack-vs-heap',
      'new-delete',
      'new-array-delete-array',
      'memory-leak',
      'dangling-pointer',
      'double-delete',
      'practice-dynamic-mem',
      'deep-vs-shallow',
      'copy-constructor',
      'copy-assignment',
      'rule-of-three',
      'practice-copy',
      'raii-concept',
      'raii-in-action',
      'raii-beyond-memory',
      'practice-raii',
      'move-motivation',
      'rvalue-reference',
      'move-constructor',
      'phase10-review',
    ],
  },
  {
    id: 'modern-cpp-start',
    badge: '现代',
    title: '现代 C++ 起点',
    description: '左值右值、移动语义、完美转发——C++11 最重要的发明。',
    courseIds: [
      'lvalue-vs-rvalue',
      'std-move',
      'move-assignment',
      'rule-of-five',
      'practice-move',
      'perfect-forwarding-motivation',
      'forwarding-reference',
      'std-forward',
      'reference-collapsing',
      'practice-forwarding',
    ],
  },
  {
    id: 'generic-programming',
    badge: '进阶',
    title: '泛型编程',
    description: '函数模板、类模板、特化、偏特化——从具体类型到通用代码。',
    courseIds: [
      'why-template',
      'function-template',
      'template-instantiation',
      'template-type-deduction',
      'class-template',
      'template-member-func',
      'practice-template-basics',
      'multi-template-params',
      'non-type-template-params',
      'template-specialization',
      'partial-specialization',
      'practice-template-advanced',
      'typename-vs-class',
      'template-compilation-model',
      'phase12-review',
    ],
  },
  {
    id: 'stl-containers',
    badge: '核心',
    title: 'STL 容器',
    description: 'vector、list、map、set——不再自己造轮子。',
    courseIds: [
      'what-is-stl',
      'vector-intro',
      'vector-operations',
      'vector-capacity',
      'list-intro',
      'deque-intro',
      'container-choose',
      'practice-seq-containers',
      'stack-queue',
      'priority-queue',
      'set-intro',
      'map-intro',
      'unordered-set-map',
      'set-vs-unordered',
      'practice-assoc-containers',
      'container-summary',
      'phase13-review',
    ],
  },
  {
    id: 'stl-algorithms',
    badge: '核心',
    title: 'STL 算法',
    description: '迭代器、算法、Lambda——用算法替代手写循环，写出地道 C++。',
    courseIds: [
      'what-is-iterator',
      'iterator-categories',
      'why-algorithms',
      'sort',
      'find',
      'count',
      'practice-find-sort',
      'lambda-intro',
      'lambda-capture',
      'for-each',
      'transform',
      'copy-remove_if',
      'algorithm-pipeline',
      'practice-algorithms',
      'phase14-review',
    ],
  },
  {
    id: 'modern-cpp-features',
    badge: '现代',
    title: '现代 C++ 特性',
    description: 'auto、decltype、范围 for、constexpr、optional——C++17/20 日常利器。',
    courseIds: [
      'auto-keyword',
      'decltype',
      'range-for',
      'structured-binding',
      'constexpr',
      'static-assert',
      'practice-modern-features',
      'nullptr-modern',
      'optional',
      'variant',
      'any',
      'phase15-review',
    ],
  },
  {
    id: 'compilation-memory',
    badge: '深入',
    title: '内存与你',
    description: '编译流程、链接、内存布局、位运算——理解你的程序如何变成机器码。',
    courseIds: [
      'compilation-steps',
      'preprocessor',
      'header-guards',
      'how-include-works',
      'decl-vs-defn',
      'one-definition-rule',
      'translation-unit',
      'practice-compilation',
      'linking-errors',
      'memory-layout',
      'stack-deep',
      'heap-deep',
      'struct-padding',
      'practice-memory-layout',
      'bitwise-operators',
      'bit-fields',
      'phase16-review',
    ],
  },
  {
    id: 'smart-ptr-type-safety',
    badge: '现代',
    title: '智能指针与类型安全',
    description: 'unique_ptr、shared_ptr、weak_ptr、类型转换——告别裸指针和 C 风格转型。',
    courseIds: [
      'unique-ptr-motivation',
      'unique-ptr-basics',
      'unique-ptr-transfer',
      'unique-ptr-container',
      'shared-ptr-intro',
      'weak-ptr',
      'make-shared',
      'smart-ptr-choose',
      'practice-smart-ptr',
      'static-cast',
      'dynamic-cast',
      'const-cast-reinterpret',
      'c-style-cast-problem',
      'practice-casting',
      'phase17-review',
    ],
  },
  {
    id: 'concurrency-basics',
    badge: '进阶',
    title: '并发入门',
    description: '线程、互斥锁、死锁、条件变量、async、atomic——进入多线程世界。',
    courseIds: [
      'why-concurrency',
      'thread-basics',
      'thread-detach',
      'data-race',
      'mutex-intro',
      'lock-guard',
      'unique-lock',
      'practice-mutex',
      'deadlock',
      'deadlock-avoidance',
      'condition-variable',
      'async-future',
      'atomic-intro',
      'practice-concurrency',
      'phase18-review',
    ],
  },
  {
    id: 'engineering-cpp',
    badge: '工程',
    title: '工程化——设计模式/构建/测试',
    description: '设计模式、C++ 惯用法、SFINAE/Concepts、CMake、测试——写出可维护的工程代码。',
    courseIds: [
      'singleton-pattern',
      'singleton-thread-safe',
      'factory-pattern',
      'observer-pattern',
      'practice-patterns',
      'pimpl-idiom',
      'crtp',
      'practice-idioms',
      'sfinae-concept',
      'enable-if',
      'concepts-cpp20',
      'cmake-basics',
      'cmake-targets',
      'why-testing',
      'gtest-basics',
      'test-organization',
      'phase19-review',
    ],
  },
  {
    id: 'cpp-deep-black',
    badge: '大师',
    title: 'C++ 深度黑话',
    description: 'ADL、RVO/NRVO、类型擦除、变参模板、内存序、UB 哲学——C++ 宇宙的尽头。',
    courseIds: [
      'adl',
      'rvo-nrvo',
      'copy-elision-cpp17',
      'type-erasure',
      'function-implementation',
      'any-implementation',
      'practice-type-erasure',
      'variadic-templates',
      'fold-expressions',
      'practice-variadic',
      'memory-order-intro',
      'memory-order-modes',
      'rtti-cost',
      'practice-advanced-concepts',
      'undefined-behavior',
      'ub-not-error',
      'zero-overhead',
      'you-pay-only',
      'cpp-philosophy-review',
      'final-reflection',
    ],
  },
  /* ── SQL / 数据库 课程 ──────────────────────────── */
  {
    id: 'db-ch1-theory',
    badge: '理论',
    title: '第1章 · 数据库核心理论',
    description: 'DB/DBMS/DBS 辨析、E-R 图三要素与联系类型、数据类型选择、五大约束——理论概念全面回顾。',
    courseIds: [
      'db-core-concepts',
      'db-core-practice',
      'db-er-practice',
      'db-data-types',
      'db-data-types-practice',
      'db-constraints',
      'db-constraints-practice',
      'db-ch1-review',
    ],
  },
  {
    id: 'db-ch2-adv-concepts',
    badge: '进阶',
    title: '第2章 · 事务·视图·索引',
    description: 'ACID 四大特性、事务语法、视图的作用与语法、索引机理与使用禁忌。',
    courseIds: [
      'db-transaction-acid',
      'db-acid-practice',
      'db-views',
      'db-indexes',
      'db-views-indexes-practice',
      'db-ch2-review',
    ],
  },
  {
    id: 'db-ch3-sql',
    badge: '实操',
    title: '第3章 · SQL 语法实操',
    description: 'DDL 建库建表、DML 增删改、SELECT 查询、聚合/分组/JOIN/子查询——全套 SQL 操作。',
    courseIds: [
      'db-ddl',
      'db-ddl-practice',
      'db-dml',
      'db-dml-practice',
      'db-basic-query',
      'db-basic-query-practice',
      'db-aggregate-groupby',
      'db-join-subquery',
      'db-advanced-query-practice',
    ],
  },
  {
    id: 'db-ch4-challenge',
    badge: '综合',
    title: '第4章 · 综合挑战',
    description: 'E-R 图转关系模式设计 + 综合 SQL 10 题——期末模拟实战。',
    courseIds: [
      'db-er-to-schema',
      'db-comprehensive-sql',
    ],
  },
]
